Repository mdsreq-fga-unb/2025.1-T02-ConsultTributario, pull requests merged in 2025-05, with the labels that each got.

#26 [Frontend] Criando Home page e lista de perguntas
  .gitignore
  components.json
  next.config.js
  package-lock.json
  package.json
  postcss.config.mjs
  public/image.png
  src/app/ login/page.tsx
  src/app/components/Footer/Footer.tsx
  src/app/components/Navbar/Navbar.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/app/perguntas/adicionar/page.tsx
  src/app/perguntas/page.tsx
  src/app/signUp/page.tsx
  src/components/ui/button.tsx
  src/components/ui/card.tsx
  src/lib/utils.ts
  tailwind.config.js
Labels: component: frontend

#27 [DOC] Adiciona primeira versão do DoR e DoD e Backlog
  docs/visao-produto/dor-dod.md
  docs/visao-produto/product-backlog.md
  mkdocs.yml
Labels: documentation

#32 docs: Atualização do Cronograma de Entregas
  docs/visao-produto/cronograma-entrega.md
Labels: documentation, enhancement

#35 [feat/auth] Implementa sistema de autenticação JWT com guards
  .github/workflows/ci.yml
  package-lock.json
  package.json
  src/api/user.ts
  src/app/ login/page.tsx
  src/app/(admin)/admin/page.tsx
  src/app/(admin)/layout.tsx
  src/app/(admin)/users/page.tsx
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/register/page.tsx
  src/app/(protected)/dashboard/page.tsx
  src/app/(protected)/layout.tsx
  src/app/components/Navbar/Navbar.tsx
  src/app/layout.tsx
  src/app/signUp/page.tsx
  src/auth/README.md
  src/auth/context/jwt/auth-consumer.tsx
  src/auth/context/jwt/auth-context.tsx
  src/auth/context/jwt/auth-provider.tsx
  src/auth/context/jwt/utils.ts
  src/auth/guard/auth-guard.tsx
  src/auth/guard/guest-guard.tsx
  src/auth/guard/role-based-guard.tsx
  src/auth/hooks/use-auth-context.ts
  src/auth/index.ts
  src/components/navigation/auth-navigation.tsx
  src/types/auth.ts
  src/utils/axios.ts
  yarn.lock
Labels: documentation, enhancement, scope: frontend, scope: backend, scope: infrastructure

#42 docs: #36 README.md
  README.md
Labels: bug, documentation, status: completed, scope: docs

#43 docs: #36 README ajustado
  README.md
Labels: bug, documentation, status: ready, priority:must, scope: docs
