Repository mdsreq-fga-unb/2025.1-T02-ConsultTributario, pull requests merged in 2025-06, with the labels that each got.

#52 [Frontend] Adiciona US-03: Criar tese tributária
  src/api/taxType.ts
  src/app/biblioteca-teses/page.tsx
  src/components/perguntas/criar-pergunta-dialog.tsx
  src/components/perguntas/editar-pergunta-dialog.tsx
  src/components/teses/cadastrar-tese.tsx
  src/components/teses/editar-tese.tsx
  src/types/claim.ts
  src/types/taxType.ts
  src/utils/axios.ts
Labels: scope: frontend, scope: backend

#60 [Frontend] Adiciona sistema de autenticação
  src/app/(admin)/admin/page.tsx
  src/app/(admin)/biblioteca-teses/cadastrar-nova/page.tsx
  src/app/(admin)/biblioteca-teses/editar-tese/[id]/page.tsx
  src/app/(admin)/layout.tsx
  src/app/(admin)/perguntas/page.tsx
  src/app/(admin)/users/page.tsx
  src/app/(auth)/login/page.tsx
  src/app/(protected)/biblioteca-teses/page.tsx
  src/app/(protected)/dashboard/page.tsx
  src/app/(protected)/diagnosticos/[id]/page.tsx
  src/app/(protected)/diagnosticos/novo-diagnostico/page.tsx
  src/app/(protected)/diagnosticos/page.tsx
  src/app/(protected)/layout.tsx
  src/app/biblioteca-teses/editar-tese/page.tsx
  src/app/components/Footer/Footer.tsx
  src/app/components/Navbar/Navbar.tsx
  src/auth/context/jwt/auth-provider.tsx
  src/auth/context/jwt/utils.ts
  src/auth/guard/auth-guard.tsx
  src/auth/guard/guest-guard.tsx
  src/auth/guard/role-based-guard.tsx
  src/auth/hooks/use-role-permission.ts
  src/auth/index.ts
  src/components/examples/role-based-access-example.tsx
  src/components/navigation/auth-navigation.tsx
  src/types/auth.ts
  src/utils/axios.ts
  yarn.lock
Labels: scope: frontend

#58 [Front-end] Adicionando tela de categoria e fatorando a tela de login e de registro
  package-lock.json
  package.json
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/register/page.tsx
  src/app/(protected)/biblioteca-teses/page.tsx
  src/app/categoria/page.tsx
  src/app/components/Navbar/Navbar.tsx
  src/app/globals.css
  src/components/ui/alert-dialog.tsx
  src/components/ui/alert.tsx
  src/components/ui/button.tsx
  src/components/ui/input.tsx
  src/components/ui/table.tsx
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/hooks/use-toast.ts
  yarn.lock
Labels: component: frontend, scope: frontend
